server:
  port: 8761 # Puerto fijo, no negociable

spring:
  application:
    name: SERVICE-DISCOVERY
  cloud:
    config:
      enabled: false # ¡IMPORTANTE! Le dice: "No busques config server, arranca ya"
    loadbalancer:
      ribbon:
        enabled: false # Desactiva balanceadores viejos para ahorrar RAM

eureka:
  instance:
    hostname: service-discovery
    prefer-ip-address: true
  client:
    register-with-eureka: false # Él es el servidor, no se registra a sí mismo
    fetch-registry: false       # No descarga la lista, él TIENE la lista
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  server:
    enable-self-preservation: false # Para desarrollo, si uno muere, lo borra rápido
    wait-time-in-ms-when-sync-empty: 5

# Configuración visual (opcional, para que no llene el log de basura)
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO