
server:
  port: 8900

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      hibernate:
        SQL: INFO
      springframework:
        web: INFO
        data: INFO
      boot:
        autoconfigure:
          data:
            rest: INFO
            jpa: INFO
            orm: INFO

